# Generated by Django 5.0 on 2025-01-03 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('MDQ', 'Mood Disorder Questionnaire'), ('BSDS', 'Bipolar Spectrum Diagnostic Scale')], max_length=4)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('mdq_yes_answers', models.IntegerField(blank=True, null=True)),
                ('mdq_same_time_period', models.BooleanField(blank=True, null=True)),
                ('mdq_problem_level', models.IntegerField(blank=True, null=True)),
                ('bsds_checked_statements', models.IntegerField(blank=True, null=True)),
                ('bsds_story_fit', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
